spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/roombooking
    username: your_pg_user
    password: your_pg_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080